[metadata]
name = disertatie2025-client-api
version = 0.1.0
author = Daniel Guceanu
description = Python client for disertatie2025-API
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT

[options]
packages = find:
install_requires =
    requests

[options.packages.find]
where = src
